language: cpp
compiler: 
    - g++

install:
    - if ["$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - cmake
    - cmake-data
    
script: 
  - ./travis-build.sh

  - cd MQTTSNGateway
  - make SENSORNET="xbee"
  - make SENSORNET="udp"  
  - make SENSORNET="udp6"
  
  - make test
    
  - cd GatewayTester
  - make 
  
notifications:
  emails:
    - tomoaki@tomy-tech.com
    
